### ISSUE TITLE
addon problem

### ISSUE THREAD

**Issue by hardWorker254** [Pyogenics/SCPG-reverse-engineering#1]
`I have a small problem, can you help me please?`
![IMG_20230907_181230 2](https://github.com/Pyogenics/SCPG-reverse-engineering/assets/144356904/d6ea89be-9156-4bce-95c8-54111efaec70)

**Comment by Pyogenics** [comment]
Sorry, the most recent commit doesn't work, try using an older version. If you have trouble I will follow up this message with a known working version.

**Comment by hardWorker254** [comment]
I found working commit, thank you
