### ISSUE TITLE
Hi, there is a problem with installing the addon.

### ISSUE THREAD

**Issue by PlanetsSub** [Pyogenics/SCPG-reverse-engineering#2]
Blender version 3.6.1
(P.s Thank you in advance)

![5134542524](https://github.com/Pyogenics/SCPG-reverse-engineering/assets/99918223/1ba5f63c-58c1-4fc6-9f1d-1e2f3e7fc019)
![image](https://github.com/Pyogenics/SCPG-reverse-engineering/assets/99918223/158e9275-5c6e-4e55-86d2-70515cadc79f)

**Comment by Pyogenics** [comment]
Sorry, the most recent version of the plugin is broken; you could try an older version.

**Comment by PlanetsSub** [comment]
V 3.6.0 
What else could be the problem._.

![image](https://github.com/Pyogenics/SCPG-reverse-engineering/assets/99918223/f1c6f545-6263-4683-8d19-10188114e5ce)

**Comment by PlanetsSub** [comment]
Oh, sorry, you were talking about the plugin... I'm just sitting through a translator

**Comment by PlanetsSub** [comment]
Thank

![image](https://github.com/Pyogenics/SCPG-reverse-engineering/assets/99918223/448ee177-2c78-4a95-912d-22fa46ed371b)

**Comment by Pyogenics** [comment]
Great, let me know if you need anything else.
