### ISSUE TITLE
CANNOT EXPORT IN SCG FORMAT

### ISSUE THREAD

**Issue by ADL650** [Pyogenics/SCPG-reverse-engineering#3]
Hi, after I install the addons, I can import scg file but how to export it in scg format? There is no DAVA scene (.scg/.sc2) on export tab.
![Screenshot (49)](https://github.com/Pyogenics/SCPG-reverse-engineering/assets/133973239/5b64656c-000f-40ca-b009-ea939c701e7d)

**Comment by Pyogenics** [comment]
Sorry there is no export function yet, potentially in the future there will be. There are some small things that need to be sorted out + a proper rewrite before I'll add that though.

**Comment by ReDKoDeZ0000** [comment]
I'm looking forward to it, I understand you are also tired of WotB monopoly mods?

**Comment by AAAOldSix666** [comment]
i'm also wishing it can complete quickly ! But I am most concerned about when the_. sg2_ file can be read
