### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by AAAOldSix666** [Pyogenics/SCPG-reverse-engineering#8]
After adding this plugin,blender 4.1 and 3.6 could only open _.scg_ file but _.sc2_  could not be opened .
![image1](https://github.com/Pyogenics/WOTBSCPGFormat/assets/163616648/1916c497-8a76-49b2-84f9-9f9aa4aefa7a)

**Comment by Pyogenics** [comment]
SC2 files can be read by the plugin but the data isn't imported into blender yet, I was working on that a while ago but lost motivation. Might get back into working on it soon.
